---
#
# My inventory file for managed/unmanaged nodes.
#

ungrouped:
  hosts:
    # The local development computer.
    localhost:
      ansible_connection: local

devenv:
  hosts:
  # Stephen's primary (Mac) laptop.
    maeve.netdavis.net:
      ansible_user: stephen
      private_ip: 192.168.1.26
      private_ip_interface: en0
      ansible_port: 22

server:
  hosts:
    # Stephen's RPi 4B (4GB).
    bob.netdavis.net:
      ansible_user: pi
      ansible_ssh_host: 192.168.1.171
      ansible_port: 22
