---
# This playbook is intended to be run by Packer, from within a VM provisioned by Packer.
#
# Usage: this playbook can be run, as follows:
#
#    $ ./pw pdm run --venv in-project ansible-playbook servers.yml

- name: Configure basic server security
  hosts: new_bob
  become: true
  gather_facts: true
  tasks:
    - name: Import ansible-prep role
      ansible.builtin.import_role:
        name: ansible_prep

    - name: Import security role
      ansible.builtin.import_role:
        name: security

- name: Configure bob as time synchronization server
  hosts: bob
  become: true
  gather_facts: true
  tasks:
    - name: Import chrony role
      ansible.builtin.import_role:
        name: chrony
