---
# This playbook is intended to be run by Packer, from within a VM provisioned by Packer.
#
# Usage: this playbook can be run, as follows:
#
#    $ ./pw pdm run --venv in-project ansible-playbook servers.yml

- name: Configure security settings
  hosts: servers
  become: true
  gather_facts: true
  tasks:
    - name: Import ansible-prep role
      ansible.builtin.import_role:
        name: ansible_prep

    - name: Import security role
      ansible.builtin.import_role:
        name: security
