---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Copy custom fail2ban configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/fail2ban/{{ item }}"
    state: present
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    validate: 'fail2ban-client -t'
    backup: yes
  loop:
    - jail.local
    - fail2ban.local
  notify: reload fail2ban

- name: Ensure fail2ban is running and enabled at boot
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

# fail2ban and auth logs are owned by the adm group.
- name: "Add user {{ security_localadmin_username }} to adm group"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: adm
    append: yes

- ansible.builtin.import_tasks: fail2ban_email_notifications.yml
  when: security_fail2ban_email_notifications_enabled | bool
