---
- name: "Ensure the {{ security_localadmin_default_group }} group exists"
  ansible.builtin.group:
    name: "{{ security_localadmin_default_group }}"
    gid: "{{ security_localadmin_gid }}"
    state: present

- name: "Create user {{ security_localadmin_username }} with default group"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    password: "{{ security_localadmin_password | ansible.builtin.password_hash }}"
    comment: "{{ security_localadmin_description }}"
    uid: "{{ security_localadmin_uid }}"
    group: "{{ security_localadmin_default_group }}"
    create_home: yes
    shell: /bin/bash
    state: present

- name: "Add user {{ security_localadmin_username }} to custom groups"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: "{{ item }}"
    append: yes
  loop: "{{ security_localadmin_additional_groups }}"
  when: security_localadmin_additional_groups | length > 0
