---

- name: "Ensure the {{ security_localadmin_username }} group exists"
  ansible.builtin.group:
    name: "{{ security_localadmin_username }}"
    gid: "{{ security_localadmin_uid_and_gid }}"
    state: present
  become: yes

- name: "Create user {{ security_localadmin_username }} with default group"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    password: "{{ security_localadmin_password | ansible.builtin.password_hash }}"
    comment: "{{ security_localadmin_description }}"
    uid: "{{ security_localadmin_uid_and_gid }}"
    group: "{{ security_localadmin_username }}"
    create_home: yes
    shell: /bin/bash
    state: present
  become: yes

- name: "Add user {{ security_localadmin_username }} to custom groups"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: "{{ item }}"
    append: yes
  with: "{{ security_localadmin_groups }}"
  become: yes
  when: security_localadmin_groups | length > 0
