---

- name: "Ensure the {{ security_localadmin_username }} group exists"
  ansible.builtin.group:
    name: "{{ security_localadmin_username }}"
    gid: "{{ security_localadmin_uid_and_gid }}"
    state: present
  become: yes

- name: "Create user {{ security_localadmin_username }} with default group"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    password: "{{ security_localadmin_password | ansible.builtin.password_hash }}"
    comment: "{{ security_localadmin_description }}"
    uid: "{{ security_localadmin_uid_and_gid }}"
    group: "{{ security_localadmin_username }}"
    create_home: yes
    shell: /bin/bash
    state: present
  become: yes

- name: "Add user {{ security_localadmin_username }} to custom groups"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: "{{ item }}"
    append: yes
  with: "{{ security_localadmin_groups }}"
  become: yes
  when: security_localadmin_groups | length > 0

- name: Check if running Raspberry Pi OS or some derivative of it
  ansible.builtin.stat:
    path: /boot/firmware/config.txt
  register: rpi

- name: Include variables for Raspberry Pi OS
  include_vars: Raspios.yml
  when: rpi.stat.exists

- name: Include variables for Ubuntu
  include_vars: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Check for default user account
  ansible.builtin.user:
    name: "{{ security_localadmin_default_account }}"
  register: user_result
  ignore_errors: True

- name: Remove default user account
  ansible.builtin.user:
    name: "{{ security_localadmin_default_account }}"
    state: absent
    remove: yes
  become: yes
  when: not user_result.failed

- name: Lock the root account
  ansible.builtin.user:
    name: root
    password_lock: yes
  become: yes
