---

- ansible.builtin.import_tasks: localadmin.yml

- ansible.builtin.import_tasks: sudoers.yml

- ansible.builtin.import_tasks: remove_default_account.yml
  when:
    - (ansible_os_family == 'Debian') and (security_remove_default_account | bool)

- ansible.builtin.import_tasks: ssh.yml
