---
- name: Ensure the SSH daemon is running
  ansible.builtin.service:
    name: ssh
    enabled: "{{ security_sshd_enabled }}"
    state: "{{ security_sshd_state }}"
  become: yes

- name: Create User .ssh Directory
  ansible.builtin.file:
    state: directory
    dest: "/home/{{ account.localuser.username }}/.ssh"
    mode: u=rwx,g=,o= 
    owner: "{{ account.localuser.username }}"
    group: "{{ account.localuser.username }}"
  become: yes

- name: Authorize SSH Key
  ansible.posix.authorized_key:
    user: "{{ account.localuser.username }}"
    key: "{{ account.localuser.ssh_key.public }}"
  become: yes

- name: Copy SSH Public Key
  ansible.builtin.copy: 
    content: "{{ account.localuser.ssh_key.public }}" 
    dest: "/home/{{ account.localuser.username }}/.ssh/id_rsa.pub"
    owner: "{{ account.localuser.username }}"
    group: "{{ account.localuser.username }}"
    mode: u=rw,g=r,o=r
  become: yes

- name: Create SSH Deamon Config File
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes

- name: Ensure sshusers Group Exists
  ansible.builtin.group:
    name: sshusers
    state: present
  become: yes

- name: "Add {{ account.localuser.username }} to sshusers Group"
  # This seems redundant with the above sudoers.d entry, but is needed by polkit.
  ansible.builtin.user:
    name: "{{ account.localuser.username }}"
    groups: sshusers
    append: yes
  become: yes

- name: Ensure SSH Daemon Starts at Boot
  ansible.builtin.service:
    name: ssh
    enabled: yes
  become: yes
