---
- name: Ensure the SSH daemon is running
  ansible.builtin.service:
    name: ssh
    enabled: "{{ security_sshd_enabled }}"
    state: "{{ security_sshd_state }}"
  become: yes

- name: "Create {{ security_localadmin_username }}'s SSH directory"
  ansible.builtin.file:
    state: directory
    dest: "/home/{{ security_localadmin_username }}/.ssh"
    mode: u=rwx,g=,o= 
    owner: "{{ security_localadmin_username }}"
    group: "{{ security_localadmin_username }}"
  become: yes

- name: Authorize the SSH key
  ansible.posix.authorized_key:
    user: "{{ security_localadmin_username }}"
    key: "{{ security_ssh_public_key }}"
  become: yes

- name: Copy the SSH public key
  ansible.builtin.copy: 
    content: "{{ security_ssh_public_key }}" 
    dest: "/home/{{ security_localadmin_username }}/.ssh/{{ security_ssh_public_key_filename }}"
    owner: "{{ security_localadmin_username }}"
    group: "{{ security_localadmin_username }}"
    mode: u=rw,g=r,o=r
  become: yes

- name: Create the SSH deamon config file
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes

- name: Ensure the sshusers group exists
  ansible.builtin.group:
    name: sshusers
    state: present
  become: yes

- name: "Add {{ security_localadmin_username }} to the sshusers group"
  # This seems redundant with the above sudoers.d entry, but is needed by polkit.
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: sshusers
    append: yes
  become: yes

- name: Ensure the SSH daemon starts at boot
  ansible.builtin.service:
    name: ssh
    enabled: yes
  become: yes
