---
- name: "Authorize {{ security_localadmin_username }} for passwordless sudo usage, set rvim as visudo editor, and configure insults"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ security_localadmin_username }}"
    content: |
      # Set the default editor used by visudo, and do not allow visudo to use EDITOR/VISUAL.
      Defaults editor=/usr/bin/rvim, !env_editor

      # Allow the {{ security_localadmin_username }} account sudo access without requiring a password.
      Defaults:{{ security_localadmin_username }} !authenticate

      # Replace feedback with humorous insults.
      Defaults insults
    owner: root
    group: root
    mode: u=r,g=r,o=
    validate: 'visudo --check --file=%s'
  become: yes
  when: security_sudoers_passwordless | bool

# This seems redundant with the above sudoers.d entry, but is needed by polkit in case this
# role configures a graphical environment. Also it aligns with standard user administration practices.
- name: "Add {{ security_localadmin_username }} to sudo group"
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: sudo
    append: yes
  become: yes

- name: Lock the root account
  ansible.builtin.user:
    name: root
    password_lock: yes
  become: yes
  when: security_sudoers_lock_root_account | bool
