---

- name: "Authorize {{ security_localadmin_username }} for NOPASSWD sudo usage"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ security_localadmin_username }}"
    content: |
      # Allow the {{ security_localadmin_username }} account sudo access without requiring a password.
      {{ security_localadmin_username }} ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: u=w,g=r,o=
    validate: '/usr/sbin/visudo --check --file=%s'
  become: yes
  when: security_sudoers_passwordless | bool

- name: "Add {{ security_localadmin_username }} to sudo group"
  # This seems redundant with the above sudoers.d entry, but is needed by polkit in case this
  # role configures a graphical environment and aligns with standard user administration practices.
  ansible.builtin.user:
    name: "{{ security_localadmin_username }}"
    groups: sudo
    append: yes
  become: yes

- name: Lock the root account
  ansible.builtin.user:
    name: root
    password_lock: yes
  become: yes
  when: security_sudoers_lock_root_account | bool
