---

- name: Create the workspaces Directories
  ansible.builtin.file:
    state: directory
    path:  "/home/{{ account.localuser.username }}/{{ item }}"
    owner: "{{ account.localuser.username }}"
    group: "{{ account.localuser.username }}"
  loop:
    - workspaces
    - workspaces/netdavis
    - workspaces/netdavis/tools
    - workspaces/netdavis/installers
    - workspaces/netdavis/projects
  become: yes

