---

# Slightly future proofing this (shrug).
- name: Check if Raspberry Pi-Based OS
  ansible.builtin.stat:
    path: /boot/config.txt
  register: rpi

- name: Import UART configuration
  ansible.builtin.import_tasks: uart.yml
  when:
    - rpi.stat.exists
    - rpi_hardware_uart_enabled | bool
