---
security_localadmin_username: "localadmin"
security_localadmin_password: "secret"
security_localadmin_groups: []
security_localadmin_description: "Local administrator account"
security_localadmin_uid_and_gid: 1001

security_sudoers_passwordless: true
security_sudoers_lock_root_account: true

security_remove_default_account: true

security_sshd_state: "started"
security_sshd_enabled: true
security_ssh_public_key: ""
security_ssh_public_key_filename: 

security_ssh_port: 22
security_ssh_address_family: "inet"
security_ssh_listen_address: "0.0.0.0"
security_ssh_permit_root_login: "no"
security_ssh_pubkey_authentication: "yes"
security_ssh_authorized_keys_files: [".ssh/authorized_keys"]
security_ssh_authorized_keys_command: "none"
security_ssh_authorized_keys_command_user: "nobody"
security_ssh_authorized_principals_file: "none"
security_ssh_password_authentication: "no"
security_ssh_challenge_response_authentication: "no"
security_ssh_authentication_methods: "publickey"
security_ssh_use_pam: "no"
security_ssh_allowed_users: []
security_ssh_allowed_groups: []
security_ssh_client_alive_interval: 300
security_ssh_client_alive_count: 0
security_ssh_login_grace_time: "1m"
security_ssh_max_auth_tries: 3
security_ssh_max_sessions: 10
security_ssh_max_startups: "10:30:60"
security_ssh_permit_tunnel: "no"
security_ssh_allow_agent_forwarding: "no"
security_ssh_allow_tcp_forwarding: "no"
security_ssh_tcp_keep_alive: "yes"
security_ssh_gateway_ports: "no"
security_ssh_rekey_limit: "default none"
security_ssh_strict_modes: "yes"
security_ssh_ignore_rhosts: "yes"
security_ssh_host_based_authentication: "no"
security_ssh_permit_empty_passwords: "no"
security_ssh_permit_user_environment: "no"
security_ssh_use_dns: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_gss_api_cleanup_credentials: "yes"
security_ssh_gss_api_strict_acceptor_check: "yes"
security_ssh_gss_api_key_exchange: "no"
security_ssh_kerberos_authentication: "no"
security_ssh_kerberos_or_local_password: "yes"
security_ssh_kerberos_ticket_cleanup: "yes"
security_ssh_kerberos_get_afs_token: "no"
security_ssh_kex_algorithms: []
security_ssh_ciphers: []
security_ssh_macs: []
security_ssh_host_keys: []
security_ssh_syslog_facility: "AUTH"
security_ssh_subsystem: ""
security_ssh_log_level: "VERBOSE"
security_ssh_x11_forwarding: "no"
security_ssh_x11_display_offset: 10
security_ssh_x11_use_localhost: "yes"
security_ssh_print_motd: "yes"
security_ssh_print_last_log: "yes"
security_ssh_kbd_interactive_authentication: "no"
security_ssh_permit_tty: "no"
security_ssh_compression: "delayed"
security_ssh_pid_file: ""
security_ssh_chroot_directory: "none"
security_ssh_accept_environment_vars: []
