---
#
# Only variables specific to the current development computer should be put here.
#

account:
  root:
    username: root
    password: "{{ vault_account.root.password }}"
    description: Benevolent Dictator
    uid_and_gid_number: 0
  localuser:
    username: stephen
    password: "{{ vault_account.localuser.password }}"
    description: Stephen A. Davis
    uid_and_gid_number: 1001
    ssh_key:
      public: "{{ vault_account.localuser.ssh_key.public }}"
      private: "{{ vault_account.localuser.ssh_key.private }}"
