---
- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: "{{ security_ssh_restart_handler_state }}"

- name: reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
